# Generated by Django 4.2.7 on 2023-12-27 19:44

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='available_seats',
            field=django_jsonform.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='media/user.jpg', null=True, upload_to='mediaMovie/profile_pics'),
        ),
    ]
