# Generated by Django 4.2.7 on 2023-12-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
        ('api', '0004_alter_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='showtime',
        ),
        migrations.AddField(
            model_name='booking',
            name='titleMovie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(null=True, to='theater.seat'),
        ),
    ]
